name: globio4env
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal=3.1.4
  - geographiclib=2.0
  - netcdf4=1.6.2
  - numpy=1.26.0
  - pandas=2.1.2
  - psutil=5.9.5
  - python=3.9.18
  - scipy=1.11.3
  - shapely=1.8.0
  - taudem=5.3.8
